services:
  - type: web
    name: metabase
    region: frankfurt
    env: docker
    plan: standard
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase:db
          property: connectionString
databases:
  - name: metabase:db
    region: frankfurt
    databaseName: metabasedb
    ipAllowList: []
